# Generated by Django 4.1.3 on 2022-11-21 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_imovel', models.PositiveIntegerField()),
                ('limite_de_hospedes', models.PositiveIntegerField()),
                ('quantidade_toilet', models.PositiveIntegerField()),
                ('pet_friendly', models.BooleanField()),
            ],
        ),
    ]
