# Generated by Django 4.1.3 on 2022-11-23 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_da_reserva', models.PositiveIntegerField(auto_created=True)),
                ('reserva_pertence_ao_anuncio', models.PositiveIntegerField()),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('preco_total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('comentario', models.CharField(max_length=320)),
                ('numero_de_hospedes', models.PositiveIntegerField()),
                ('data_hora_de_criacao', models.DateTimeField(auto_now=True)),
                ('data_hora_de_atualizacao', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
